apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openclaw.fullname" . }}
  labels:
    {{- include "openclaw.labels" . | nindent 4 }}
type: Opaque
data:
  gateway-token: {{ .Values.secrets.gatewayToken | b64enc | quote }}
  {{- if .Values.secrets.anthropicApiKey }}
  anthropic-api-key: {{ .Values.secrets.anthropicApiKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.openaiApiKey }}
  openai-api-key: {{ .Values.secrets.openaiApiKey | b64enc | quote }}
  {{- end }}
