apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jellyfin
resources:
  - namespace.yaml
  - jellyfin-media-pv.yaml
  - jellyfin-config-pv.yaml
  - media-pvc.yaml
  - config-pvc.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml