variable "compartment_id" {
  type        = string
  description = "The compartment to create the resources in"
  
  default = "ocid1.tenancy.oc1..aaaaaaaazmshxiol4bmgetsexq7e3bgww7jui2o6mdsg62oxpnbmz2pqvfnq"
}

variable "region" {
  description = "OCI region"
  type        = string

  default = "ap-mumbai-1"
}

variable "ssh_public_key" {
  description = "SSH Public Key used to access all instances"
  type        = string

  default = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDGtTIzrlxEGS8VWM4IvMYKZRCnmdd/qYTCB1RwOyWt2maDd5r6P6/i15zeoy3KcVsMo0YFtWOnEI8O6U/UeVsc/9AHNtJLniPkXeu7n4FDis6pJ+yqmNOE7X9eYTVx0WgRlaV094e4t6DTTBt8dnkkpikmbvRxNW/QzUYMQsDjXZP2lOTjwU0bNgde0hlFdKALXzx0wr1ViR4qpItHRh2bhTPTrw/gROCpgm8rTwa8gVdeueYKV7zmw2MzjU3NHrbsX4uv/NgylMUrJwQ8N4BZcbEoDPFY2iStO/wola878dKKhsMIL6HcCeDi5aX+Y759xDno0g6xkmbTUiXiR7vWbC0eAwuPVwnh/jB38D9XB1HXOKH9be2X2SvVuSk8Y6OCtyk56ojqOpnpK1Nbk3Jj6E9ppd2jFosgYvVEjIfh3KQ92O8P6kpynx3WdSyskhiol4kC0R1C2X/v53CVM4fVV9Mjwiamg+7qm0gr/XrqkG7Mr33FhC4hR5SV+qGnHizA46W0ijAr4P9tqLns8Z4NHEyDOr3oIc9QbA9vSIYOqDrPGc5rQLfiAznqn+qNEt72NpKSlsYi6o0GF8Nvf75UqRNxf2ccmt5aVMbaFqZAZYl/M0b4FfQalCZmSbODm+7wCX1/UDxYXGgw+wV4yVLKlcBPFKIsYapBTkSff4wi8w== Generated By Termius"
}

variable "kubernetes_version" {
  # https://docs.oracle.com/en-us/iaas/Content/ContEng/Concepts/contengaboutk8sversions.htm
  description = "Version of Kubernetes"
  type        = string

  default = "v1.32.1"
}

variable "kubernetes_worker_nodes" {
  description = "Worker node count"
  type        = number

  default = 1
}
