apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - external-secrets/flux.yaml
  - ingress-nginx/flux.yaml
  - metrics-server/flux.yaml
  - azure-storage/flux.yaml