apiVersion: v1
kind: ConfigMap
metadata:
  name: azure-cred-file
  namespace: kube-system
data:
  azure.json: |
    {
        "cloud": "AzurePublicCloud",
        "tenantId": "",
        "subscriptionId": "",
        "resourceGroup": "",
        "location": "",
        "useManagedIdentityExtension": false,
        "useInstanceMetadata": false,
        "aadClientId": "",
        "aadClientSecret": "",
        "storageAccountName": "kshitizvmstorageaccount",
        "storageAccountKey": "PN5K7rQOs+UF+RYIrE9uWDoTU14k2z//8/rpUHU5Hh+W/sLuH2g80nGVepxr2ddULkdTFohCAh7V+AStXwN7ww=="
    } 