apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: azure-storage-secret
  namespace: kube-system
spec:
  refreshInterval: "1h"
  secretStoreRef:
    kind: ClusterSecretStore
    name: oracle-vault
  target:
    name: azure-secret
    creationPolicy: Owner
  data:
    - secretKey: azurestorageaccountname
      remoteRef:
        key: azurestorageaccountname
    - secretKey: azurestorageaccountkey
      remoteRef:
        key: azurestorageaccountkey