apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: azure-storage
  namespace: flux-system
spec:
  interval: 1h
  path: ./gitops/core/azure-storage
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      name: shared-storage
      namespace: azure-storage 