apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: azure-storage
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./gitops/core/azure-storage
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: kube-system
  wait: true 